name: CI - Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3    # v3 est deprecated, on passe à v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2    # v2 → v3 (plus récent et maintenu)

      - name: Build Backend Image
        run: |
          docker build -t tp-backend ./backend

      - name: Build Frontend Image
        run: |
          docker build -t tp-frontend ./frontend

      - name: Build Database Image
        run: |
          docker build -t tp-db ./database

      - name: List Docker Images
        run: |
          docker images
