name: CI - Test de Base                  # Nom du workflow

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"
      - "frontend/**"

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 2 * * *"    # Tous les jours à 2h00 UTC

  workflow_dispatch:       # Permet de lancer le workflow manuellement
jobs:                                     # Ensemble des jobs
  hello:
    runs-on: ubuntu-latest                # Environnement du runner

    steps:                                # Étapes du job
      - name: Afficher un message
        run: echo "CI fonctionne !"
